<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Others</name>
   <tag></tag>
   <elementGuidId>b850494c-b9d0-41b6-8171-457bcda1c5ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/sa-navigation/aside/nav/ul/li[21]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/sa-navigation/aside/nav/ul/li[21]/a/i</value>
      <webElementGuid>d820053f-b165-4135-b6b0-1bedd2095c73</webElementGuid>
   </webElementProperties>
</WebElementEntity>
