<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_Mnr</name>
   <tag></tag>
   <elementGuidId>b5f67f2a-d6d6-432e-bd5f-8a41992ce6f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/sa-navigation/aside/nav/ul/li[18]/ul/li[6]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/sa-navigation/aside/nav/ul/li[18]/ul/li[6]/a/span</value>
      <webElementGuid>67f615a6-388c-4384-8a2e-fcdc9cd07d03</webElementGuid>
   </webElementProperties>
</WebElementEntity>
