<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SetText_ManufactureDate</name>
   <tag></tag>
   <elementGuidId>43b734da-2390-45d7-b710-a16887fbde7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/div/sa-equipment-information/div/form/div[1]/div[2]/div/fieldset/div/div/div[1]/div[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/div/sa-equipment-information/div/form/div[1]/div[2]/div/fieldset/div/div/div[1]/div[4]/input</value>
      <webElementGuid>93c9b664-7278-42c7-b8c2-c39adcdb0046</webElementGuid>
   </webElementProperties>
</WebElementEntity>
