<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SetText_MaxPayload</name>
   <tag></tag>
   <elementGuidId>2307d049-74a2-4443-97be-f4bddcec8bdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/div/sa-equipment-information/div/form/div[1]/div[2]/div/fieldset/div/div/div[2]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/div/sa-equipment-information/div/form/div[1]/div[2]/div/fieldset/div/div/div[2]/div[3]/input</value>
      <webElementGuid>cb88d325-d10e-4b32-b9c9-74845408e69c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
