<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectRecord_From_Cleaning_Method_Details</name>
   <tag></tag>
   <elementGuidId>943c8dc3-8753-4bc2-a6ed-4d3ec618d321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/div/sa-cleaning-method/div/sa-shared-table/div/div[1]/div/p-table/div/div[2]/table/tbody/tr/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/div/sa-cleaning-method/div/sa-shared-table/div/div[1]/div/p-table/div/div[2]/table/tbody/tr/td[2]/div</value>
      <webElementGuid>be62acad-3339-4081-a262-4d19ac61c534</webElementGuid>
   </webElementProperties>
</WebElementEntity>
