<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SetText_Serach</name>
   <tag></tag>
   <elementGuidId>f5c2b9ec-2750-48c4-99a3-ce4f1cb9535c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/div/sa-cleaning-method/sa-cleaning-method-list/sa-shared-table/div/div[1]/div/p-table/div/div[1]/div/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/div/sa-cleaning-method/sa-cleaning-method-list/sa-shared-table/div/div[1]/div/p-table/div/div[1]/div/div/div[1]/input</value>
      <webElementGuid>898a55b1-6acb-4b35-b660-0663546a1e5f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
