<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SetText_Serach</name>
   <tag></tag>
   <elementGuidId>7c2bde12-c87f-44d2-a8eb-f03f15b18908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-main-layout/div/sa-cleaning-type/div/div/div[2]/div/div[2]/sa-shared-table/div/div[2]/div/p-table/div/div[1]/div/div/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-main-layout/div/sa-cleaning-type/div/div/div[2]/div/div[2]/sa-shared-table/div/div[2]/div/p-table/div/div[1]/div/div/div[1]/input</value>
      <webElementGuid>d32b4281-2e19-4bbf-bd7e-725c7fd5ade9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
